INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
	VALUES(10001, 'adhikrit', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES(10002, 'adhikrit', 'Get Azure Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES(10003, 'adhikrit', 'Get GCP Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES(10004, 'adhikrit', 'Learn DevOps', CURRENT_DATE(), false);